server.port=8081
spring.application.name=production-service

spring.r2dbc.url=r2dbc:mysql://127.0.0.1:3306/factory_db?serverZoneId=UTC
spring.r2dbc.username=root
spring.r2dbc.password=12345

jwt.secret=myverysecuresecretkey1234567890123456

# Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true